name: Deploy to GitHub Pages

on:
  push:
    branches:
      - project3  # or master
permissions:
  contents: write
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          sed -i "s/REPLACE_WITH_API_KEY/${{ secrets.GOOGLEAPI_KEY }}/g" map.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages 